# Generated by Django 4.2.6 on 2024-01-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('CodeCNTR', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DesignationC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CodeCL', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=20)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('CodeEMP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NomE', models.CharField(max_length=100)),
                ('AdresseE', models.CharField(max_length=200)),
                ('TelephoneE', models.CharField(max_length=20)),
                ('SalaireJ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('CodeF', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NomF', models.CharField(max_length=100)),
                ('AdresseF', models.CharField(max_length=200)),
                ('TelephoneF', models.CharField(max_length=20)),
                ('Solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('CodeP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateV', models.DateField()),
                ('montantV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statutPY', models.CharField(max_length=50)),
                ('clnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.client')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('QuantiteE', models.IntegerField()),
                ('coutE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cntr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.centre')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Masrouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateM', models.DateField()),
                ('avanceS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Achats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateA', models.DateField()),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StatutP', models.CharField(max_length=50)),
                ('quantiteA', models.IntegerField()),
                ('frn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.fournisseur')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_manager.produit')),
            ],
        ),
    ]
