# Generated by Django 4.2.6 on 2024-01-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0003_remove_fournisseur_solde_achats_solde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='coutE',
            new_name='prix_UnitaireE',
        ),
    ]
