# Generated by Django 4.2.6 on 2024-01-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0004_rename_coute_transfer_prix_unitairee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achats',
            old_name='DateA',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='achats',
            old_name='quantiteA',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='CodeCNTR',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='centre',
            old_name='DesignationC',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='AdresseE',
            new_name='Adresse',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='CodeEMP',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='NomE',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='TelephoneE',
            new_name='Telephone',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='AdresseF',
            new_name='Adresse',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='CodeF',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='NomF',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='TelephoneF',
            new_name='Telephone',
        ),
        migrations.RenameField(
            model_name='masrouf',
            old_name='DateM',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='masrouf',
            old_name='avanceS',
            new_name='avance',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='QuantiteE',
            new_name='Quantite',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='DateV',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='montantV',
            new_name='montant',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='statutPY',
            new_name='statut',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='prix_UnitaireE',
        ),
    ]
