# Generated by Django 4.2.6 on 2024-01-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0005_rename_datea_achats_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='CodeP',
            new_name='Code',
        ),
    ]
